### ISSUE TITLE
Notify the administrators when one of the installed licensed applications has a new version available

### ISSUE THREAD

**Issue by mflorea** [xwikisas/application-licensing#110]
This should be done only if automatic upgrades are turned off for that application or globally. There should also be a configuration option to disable these notifications (e.g. put a checkbox on the Licenses administration section).

The notification message could indicate that in order to disable these notifications you need to:
* either use the corresponding configuration
* or enable automatic upgrades, see #109

**Comment by oanalavinia** [comment]
-  Added a scheduler job that does a check for new versions available and sends a notification (one per application/wiki/version); this job is triggered once a week since usually upgrades are not done more frequently
-  The notification is sent to those that have these notifications (_New extension version available_) enabled and the System filter disabled, since the notification is send by superadmin user;

The notification:
![licensing_110](https://user-images.githubusercontent.com/22794181/187136151-143d4d7e-1730-4a6b-902d-315d072e928f.png)

The notifications settings:
![licensing_110_notifSettings](https://user-images.githubusercontent.com/22794181/187137128-c9b6461b-eeef-46c3-a8ad-d0de426ae93a.png)
