### ISSUE TITLE
Licenses related message is shown when inspecting the login page on an instance where a paid app (or just the Antivirus app) is installed

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-licensing#135]
Hi,

Prerequisites: 
- In order to see this, you can use an XWiki instance where a paid app is installed, or it was at some point installed and now no paid apps are left on it.
- Firefox browser

1. On the Firefox browser, open the developer tools on the Network tab
2. Access the login page of an XWiki instance
3. Check on the Network tab the 401 request related to XWikiLogin > Response (with Raw option unchecked)
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/36840106/208131135-2c842403-b3a0-4270-b9d1-d2e562dc8b45.png">

Can this be considered a security issue or a bug?

**Comment by mflorea** [comment]
Hi @AndreeaChi, some notes:
* the Antivirus Application is a paid app, so it's normal that you get the same behavior as for any other paid app
* uninstalling a paid app doesn't remove the Licensing Application; in general, when an XWiki extension has dependencies (and all paid applications depend on the Licensing Application) those dependencies are not removed automatically when you uninstalled that extension. The reason is because we can't know for sure if those dependencies are not used by something else.
* the Licensing Application provides an UI extension for ``org.xwiki.platform.notifications`` in order to warn the administrators about missing licenses in the notification menu. This is implemented by the ``Licenses.Code.LicensesNotificationsUIX`` page. So in your case since you have the bell icon even on the login page it means the notification menu is present so the notification menu UI extensions are executed, including the one provided by the Licensing Application, which fails to be executed because of missing access right for the guest user.

I don't see any problem for the end user so for me this should be closed as Won't Fix.

**Comment by AndreeaChi** [comment]
Thanks for the check, @mflorea !

**Comment by mflorea** [comment]
@AndreeaChi was there anything strange displayed in the notification menu (bell icon)? I'm trying to make sure there's no effect for the end user.

**Comment by AndreeaChi** [comment]
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/36840106/208395410-c39d41e4-c194-4c3d-a129-57549001452c.png">

I clicked on the notification bell and I see an error message shown there as well indeed.

Expanded message:
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/36840106/208395710-d0a4774d-dce8-4c27-b711-89514ea1490d.png">

**Comment by mflorea** [comment]
OK, the error message on the notification menu is not good. Reopening.

**Comment by mflorea** [comment]
We need to check for view rights in ``Licenses.Code.LicensesNotificationsUIX`` before including its content (i.e. wrap the include macro call with a view access rights check).

**Comment by oanat** [comment]
I tested this issue on the default wiki 14.10.3 with an application like Azure AD installed and I did not reproduce the same display. This is due to the rights setup for the guest user on the theme page: by default, guest users do not have view rights on the skin and the bell icon is not displayed, you have it when you hover on the area.
![Notifications](https://user-images.githubusercontent.com/370535/211905294-b121a72a-57d4-40d6-baf6-e77e8b3bb2dc.png)
On @AndreeaChi's example, there are specific rights settings on the theme (for example in a cloud wiki setup) which make the notifications bell icon available for the user.

**Comment by oanat** [comment]
I tested this issue on the default wiki 14.10.3 with an application like Azure AD installed and I did not reproduce the same display: the Notifications bell is not displayed at all  
<img width="1418" alt="DefaultXWikiLogin" src="https://user-images.githubusercontent.com/370535/212035338-990c3b34-30b2-4e0d-8b45-fcc467ae40f1.png">
If we add a view restriction for the guest 
![RightsRestriction](https://user-images.githubusercontent.com/370535/212035886-bf27ed21-d80a-4d75-9c02-7cfeb2a2acad.png)
the bell icon is not properly displayed, but you have it when you hover on the zone.
![Notifications](https://user-images.githubusercontent.com/370535/212035798-5ea1ce5e-1617-4afd-9fd3-00802b8cfd02.png)

On @AndreeaChi's example, there are specific rights settings on the theme (for example in a cloud wiki setup) which make the notifications bell icon available for the guest user.
