### ISSUE TITLE
Licences screen doesn't work: TypeError: a(...).size is not a function

### ISSUE THREAD

**Issue by fransf-wtax** [xwikisas/application-licensing#139]
When navigating to the [Licenses screen](https://xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=Licenses) on Wiki Administration, none of the buttons work.
<img width="997" alt="Screenshot 2023-01-27 at 10 22 28" src="https://user-images.githubusercontent.com/73120089/215080867-79a22ae3-7d98-464b-b0d0-178b7fad5c2d.png">

I checked the Development tools Console and found the following error that is thrown when the page loads:

```
Uncaught TypeError: a(...).size is not a function
    at WebHome?language=en&docVersion=1.1:6:161
    at Object.execCb (require.min.js?r=1:5:16727)
    at e.check (require.min.js?r=1:5:10499)
    at e.<anonymous> (require.min.js?r=1:5:12915)
    at require.min.js?r=1:5:1542
    at require.min.js?r=1:5:13376
    at each (require.min.js?r=1:5:1020)
    at e.emit (require.min.js?r=1:5:13344)
    at e.check (require.min.js?r=1:5:11058)
    at e.enable (require.min.js?r=1:5:13242)
```
<img width="423" alt="Screenshot 2023-01-27 at 10 30 18" src="https://user-images.githubusercontent.com/73120089/215080896-dd6db066-49ac-4ea2-9ff8-4be479b94e19.png">

I want to use a licensed plugin (Azure SSO integration) and I can't activate a trial or paid license now.

**Comment by acotiuga** [comment]
Hi @fransf-wtax,
I just tested the use case with 2 different extensions (Azure SSO and Diagram), latest versions and I managed to get a trial license for each of them, on clean XWiki instances v 14.10.3. 
It looks like the code causing the error is in a page with the name `WebHome`, but could you identify the full name of the page?

**Comment by fransf-wtax** [comment]
Hi @acotiuga ! I'm not sure where that comes from. The page that has the problem has the URL https://<<mywikihost>>/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=Licenses . There's nothing about `WebHome` in there so I'm not sure what happens behind the scenes to make it reference that. I don't know enough about the internal workings of XWiki to know where to look.

**Comment by fransf-wtax** [comment]
@acotiuga In my browser's network tab I *do* see a request being made to https://mywikihost.mydomain/bin/ssx/Licenses/WebHome?language=en&docVersion=1.1 . That looks like it could be the `WebHome` that's causing the issues.

**Comment by acotiuga** [comment]
@fransf-wtax What browser are you using? 
I tested in both Chrome and Firefox and I get only warnings about the need of replacing `size()` with `length` since the jQuery library has been recently upgraded. These logs should not break any functionality.

**Comment by fransf-wtax** [comment]
Chrome 109.0.5414.87.

I'll try to upgrade to XWiki 14.10 to see if that fixes it by any chance.

**Comment by fransf-wtax** [comment]
Same problem after upgrade to XWiki 14.10.3. Trying on Firefox...

**Comment by acotiuga** [comment]
You can try to restart the XWiki instance and also to clear the browsers cache. Sometimes it helps.

**Comment by acotiuga** [comment]
@fransf-wtax If your data in the License Ownership is saved, then any extension installed will get a trial by default. What you can do now is to uninstall and install again the extension and you should get automatically a trial. 
This will not fix your JS issue, but you will be able to configure and test the Azure SSO.
Hope it helps!

**Comment by fransf-wtax** [comment]
@acotiuga Sadly, the only way to save the license ownership data is to click the Trial or Buy buttons, which aren't working. I saw there was a feature request for a separate Save button, but I don't think it's been implemented yet.

I've upgraded to XWiki 14.10.3 but many of my attachments are now gone. This is turning into a nightmare!

**Comment by fransf-wtax** [comment]
Andreea from XWiki SAS support suggested the following which fixed it:
- Go to the main wiki administration > Extensions.
- Click on the "More" button > Advanced search.
- Fill in the library extension id `org.webjars:jquery-migrate` and version `3.3.2`
- Install it on farm.

I now get the warnings that @acotiuga mentioned in [his reply](https://github.com/xwikisas/application-licensing/issues/139#issuecomment-1406491973) but no more errors and the Licenses page now works as intended. I think it still means the actual code of this screen should still be fixed to use `length` instead of `size()`, but at least this seems to mitigate the issue until that has been done.

**Comment by AndreeaChi** [comment]
Writing here that from previous experience, the problem is a missing  jQuery migrator plugin library. The fix would be to install it using the steps below:

- Go to the main wiki administration > Extensions.
- Click on the "More" button > Advanced search.
- Fill in the library extension id org.webjars:jquery-migrate and version 3.3.2
- Install it on farm.

**Comment by mflorea** [comment]
@fransf-wtax the jQuery upgrade we did in https://jira.xwiki.org/browse/XWIKI-14928 (14.1) introduced some breaking changes (such as the removal of the ``size`` function) and since jQuery is used in may places, by many extensions, it was very hard to fix all those places at once. We used instead the jQuery migrate plugin to "emulate" the old jQuery APIs that were removed or broken until all extensions are updated. This jQuery migrate plugin is a dependency of the XWiki standard flavor so it should be installed **automatically**, see https://github.com/xwiki/xwiki-platform/blob/xwiki-platform-14.10.3/xwiki-platform-distribution/xwiki-platform-distribution-flavor/xwiki-platform-distribution-flavor-common/pom.xml#L261-L267 . For some reason it wasn't installed in your XWiki instance, or it was removed by mistake (maybe during some upgrade). Note that the licenses administration section is probably not the only one affected by this problem. Any extension that you have installed on top of XWiki and that uses JavaScript is potentially broken by the missing jQuery migrate plugin.
