### ISSUE TITLE
Implement feedback form feature

### ISSUE THREAD

**Issue by snazare** [xwikisas/application-licensing#172]

**Comment by oanalavinia** [comment]
Reopening since there could be problems if a Content-Security-Policy is set. This happens since we need to load JS files from the marketing server in order to generate the form.
Of course, it's not a valid solution to ask clients to add the marketing server in their CSP just to give feedback. The following solution will be implemented:
- we keep the modal with the feedback form where this is acceptable
- redirect to a feedback form on store.xwiki.com in the other cases

We would still keep the modal when it's possible, since it's better to keep users on the current site (redirecting lowers changes that users will fill in the feedback form)

**Comment by oanalavinia** [comment]
In the extensions livetable from the Licensing administration page, for each extension a new feedback button was added
![image](https://github.com/user-attachments/assets/afa9c384-4050-43f6-9517-b217a383a7b0)

This opens a modal that contains the feedback form
![image](https://github.com/user-attachments/assets/a689ed43-d689-4dc0-b818-d19b4358aef9)

Because displaying this form requires loading an external resource, it might not be possible to display this modal for instances that have a strict CSP (Content-security-policy) set. In this case, users will be redirected to our store page, where the same form is displayed.

On both cases, some information will be prefilled (instance ID, extension ID, email)
