### ISSUE TITLE
Notification bell is not marked differently when Silk Icon Theme is used

### ISSUE THREAD

**Issue by evalica** [xwikisas/application-licensing#59]
This is an usability issue. 

Users can install the (PRO) apps, but might have the "Silk Icon Theme" set instead of the default "Font Awesome Icon Theme".
After installing the app, one user continued to his page, to the Macros selector, without going through the AppBar, or noticing the Notification message. He was not aware there are further steps needed in order to complete the installation of the Pro app.

Currently the 2 default Icon Themes have no consistent behavior. 

Expected: "Font Awesome"
<img width="189" alt="FontAwesome" src="https://user-images.githubusercontent.com/629552/60340388-1f4fd780-99b4-11e9-92d7-52fd8fe58a88.png">

Current: "Silk"
<img width="200" alt="Silk" src="https://user-images.githubusercontent.com/629552/60340405-2676e580-99b4-11e9-8614-fad89dff7555.png">
<img width="430" alt="SilkExpanded" src="https://user-images.githubusercontent.com/629552/60340424-2ecf2080-99b4-11e9-95aa-f01f9ae714ae.png">

Solutions ideas: 
* (easy) add a visible marker to the bell, that is consistent through IconThemes;
* (medium) we could auto-open the Notification area to display the license message;
* (complex) clearly state in the Extension Manager that there are multiple steps to do for an application to be installed. For example: 
** Step (1/4) - when the user pressed on "Install". 
** Step (2/4) - when the user pressed on "Continue". 
** Step (3/4) - if the application is paid, he will need to go to the "Licenses". 
** Step (4/4) - encourage the user to open the application from the AppBar, or direct him to the Macros Index, highlighting the newly installed extension.

Tested with XWiki 11.5 and Calendar Pro 2.8.4.

**Comment by acotiuga** [comment]
The best solution is to properly integrate the licensor's notifications into the wiki's notification and use the same feature.
However, in order to address the current issue and to provide a (less nice) solution, a red square is wrapping the notification bell. This is more in line with the current behaviour of colouring the bell with red when Font Awesome is used.
![Screenshot from 2020-09-02 16-20-55](https://user-images.githubusercontent.com/8121819/91989131-d07c9b00-ed38-11ea-83bd-0c72d48ff4d6.png)
