### ISSUE TITLE
We shouldn't allow access to the "Licenses" area in a sub-wiki

### ISSUE THREAD

**Issue by evalica** [xwikisas/application-licensing#7]
If you successfully installed an application from the main wiki, you can after install other application from the sub-wiki. 

We should provide a redirect, or not display the Licenses section in the sub-wiki or provide a message that sends the user to the main wiki. 
<img width="631" alt="subwiki" src="https://user-images.githubusercontent.com/629552/33140806-bc095194-cfb9-11e7-9912-731383efe227.png">

**Comment by mflorea** [comment]
I added a message with a link to the main wiki. I didn't redirect the user because he may not notice the switch to the main wiki and he may continue to change the configuration thinking he is on the sub wiki.

![screenshot-2017-11-28 wiki administration - xwiki](https://user-images.githubusercontent.com/652632/33328191-0092ea08-d462-11e7-8642-c4aeadb323dd.png)
