### ISSUE TITLE
Generate application license automatically from the Extension Manager

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-licensing#92]
If the owner details are already present on the instance, generate automatically the trial license after installing the application from Extension Manager, without the need for the user to go to Licenses Administration.

**Comment by mflorea** [comment]
@oanalavinia we might have overlooked something. When **installing** a licensed application that has dependencies that also require a license, those dependencies will be installed **first** so they will be seen as mandatory / top level by our listener (which listens to any install, so it catches "intermediary" installs from the install plan). This will lead to the generation of licenses for each licensed dependency, which we don't want.

We have two use cases to cover:
* A (licensed) depends on B (licensed): we should generate a license only for A
* A depends on B (licensed): we should generate a license for B

So it looks like we should:

* either wait for all the extensions from the install plan to be installed and then check the dependency tree for licensed extensions to generate the license for
* or check the install plan when catching an install event to see if the installed extension doesn't have a "parent" that requires a license

Can you confirm the problem? I haven't checked the code. Please report an issue if the problem is present.

**Comment by oanalavinia** [comment]
Indeed, there is this problem. I opened an issue for it #97
