### ISSUE TITLE
When uninstalling an app, none of its submodules should be displayed in the License section

### ISSUE THREAD

**Issue by acotiuga** [xwikisas/application-licensing#95]
Active Directory application has Active Directory UI and Active Directory Authenticator as modules and UI depends on Authenticator. In addition, and what could be different on AD than the other paid apps, the Authenticator is installed on farm.
When uninstalling the UI, the Authenticator is not uninstalled and it is "promoted" as extension that needs a license, thus listed in the notifications and in the License section:
![image](https://user-images.githubusercontent.com/8121819/111353876-643b0680-868e-11eb-8551-d6c44f2be7fe.png)
![image](https://user-images.githubusercontent.com/8121819/111354182-b3813700-868e-11eb-811d-eea16a667274.png)

Forum app example with UI and API: if the UI is uninstalled, the API is still there but not listed in the 2 sections mentioned above.

File manager example with UI, API and dependency on PDF Viewer Macro Pro: When the UI is uninstalled, the API is still there but not listed in the 2 sections. The PDF Viewer Macro Pro is "promoted" as extension that needs a license (it wasn't listed before because was installed as dependency)

This issue seems to manifest only in the case of AD because the Authenticator is skipping the `isRequiredBy` filter from https://github.com/xwikisas/application-licensing/blob/35a6660b68ff6b98d9c422c8c19a1530a14af694/application-licensing-licensor/application-licensing-licensor-ui/src/main/resources/Licenses/Code/VelocityMacros.xml#L76. 
In addition to this filter we can check also that the extension is not considered a dependency, checking `extension.isDependency()` which will be true for AD Authenticator, but not for PDF Viewer Macro PRO, when installing as dependency of Filemanager app.
The new filter should be `#if (!$isRequiredBy && !$paidExtension.isDependency())`.
WDYT @mflorea ?

**Comment by mflorea** [comment]
@acotiuga there are two things here:

* The fact that when you uninstall an extension the Extension Manager doesn't uninstall its dependencies automatically. This is outside the scope of the licensing application, since the install / uninstall is done through the Extension Manager, standard for any extension, licensed or not.
* The fact that you _can_ see **former** dependencies (of the uninstalled licensed extension) in the Licenses administration section. This is perfectly fine when:
  * those former dependencies are _promoted_ to top level extensions because there are no other extensions that depend on them
  * those former dependencies **require a license**

In your case the Active Directory Authenticator [depends on licensor-api](https://github.com/xwikisas/application-activedirectory/blob/master/application-activedirectory-api/pom.xml#L59) so it is a licensed extension. And any licensed extension that is _top level_ (no other extension depends on it) must be listed in the Licenses administration section.

In the case of Forum and File Manager, their APIs **don't depend on the licensor-api**. So they won't be listed, obviously.

Now, you may ask: should the Forum API and the File Manager API depend on the licensor-api? When is an API module supposed to depend on the licensor-api and when not? My answer is this:

* if **simple users** can continue to use the "application" after the UI has been uninstalled then the API needs to depend on the licensor. This is the case of the "applications" whose only UI is a configuration section. The users could configure the application and then uninstall the UI and continue using the application. We want to prevent that.
* if simple users can't continue to use the application without its UI then there's no need to make the API a licensed extension. You cannot really use the Diagram Application or the File Manager application without the UI so there's no incentive to make their APIs licensed.
